name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check with mypy
        run: |
          pip3 install mypy
          mypy server.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install test dependencies
        run: |
          pip3 install pytest pytest-mock
      - name: Test with pytest
        run: |
          pytest
